'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, BrainCircuit, Loader2, Send, Trophy } from 'lucide-react'
import { useParams } from 'next/navigation'
import { Nav } from '@/components/Nav'
import { answerInterview, getInterview, getAnalysis, startInterview, type Analysis, type Interview } from '@/lib/api'

export default function InterviewPage(){
  const params=useParams<{id:string}>(); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [interview,setInterview]=useState<Interview|null>(null); const [answer,setAnswer]=useState(''); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState('')
  useEffect(()=>{(async()=>{try{const a=await getAnalysis(params.id);setAnalysis(a);const stored=typeof window!=='undefined'?localStorage.getItem(`repolens-interview-${params.id}`):null;if(stored)setInterview(await getInterview(stored))}catch(e:any){setError(e?.message)}finally{setLoading(false)}})()},[params.id])
  async function begin(){setError('');try{const i=await startInterview(params.id,8);setInterview(i);localStorage.setItem(`repolens-interview-${params.id}`,i.id)}catch(e:any){setError(e?.message)}}
  async function submit(e:FormEvent){e.preventDefault();if(!interview||!answer.trim())return;setSending(true);setError('');try{const next=await answerInterview(interview.id,answer.trim());setInterview(next);setAnswer('')}catch(e:any){setError(e?.message)}finally{setSending(false)}}
  if(loading)return <div className="min-h-screen"><Nav/><main className="mx-auto max-w-4xl px-4 py-16 text-sm text-[#77736c] sm:px-6">Loading interview…</main></div>
  const current=interview?.turns?.[interview.current_index]
  return <div className="min-h-screen"><Nav/><main className="mx-auto max-w-4xl px-4 py-7 pb-16 sm:px-6 sm:py-10 sm:pb-20">
    <Link href={`/repositories/${params.id}`} className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-[#66625b] transition hover:text-white"><ArrowLeft size={14}/> Back to repository</Link>
    <div className="mt-7 flex flex-col gap-5 border-b border-white/[.08] pb-6 sm:flex-row sm:items-end sm:justify-between reveal"><div><div className="flex items-center gap-2 text-amber-300"><BrainCircuit size={18}/> <span className="font-mono text-[10px] uppercase tracking-[.16em]">AI interviewer</span></div><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-4xl">Defend your implementation.</h1><p className="mt-2 truncate font-mono text-[11px] text-[#66625b]">{analysis?.owner}/{analysis?.repo_name}</p></div>{interview&&<div className="sm:text-right"><div className="font-mono text-[9px] uppercase tracking-wider text-[#55514b]">Progress</div><div className="mt-1 font-mono text-lg">{Math.min(interview.current_index+1,interview.turns.length)} / {interview.turns.length}</div></div>}</div>
    {error&&<div className="mt-5 border border-rose-400/20 bg-rose-400/[.05] p-3 text-sm text-rose-300 reveal">{error}</div>}
    {!interview&&<div className="card mt-7 p-5 sm:p-7 reveal"><div className="font-mono text-[9px] uppercase tracking-[.16em] text-amber-400">/ interview session</div><h2 className="mt-3 text-xl font-semibold">Project-specific questions</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#77736c]">Questions are generated from the repository architecture, languages, metrics, findings and AI review.</p><button onClick={begin} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 border border-amber-400/40 bg-amber-400 px-5 py-3 text-sm font-semibold text-black transition hover:bg-amber-300 sm:w-auto">Start interview <ArrowRight size={16}/></button></div>}
    {interview?.status==='active'&&current&&<form onSubmit={submit} className="card relative mt-7 overflow-hidden p-5 sm:p-7 reveal"><div className="scan-overlay opacity-30"/><div className="relative"><div className="flex items-center justify-between gap-4"><div className="font-mono text-[9px] uppercase tracking-[.16em] text-amber-400">Question {current.question_index+1}</div><div className="h-1.5 flex-1 max-w-36 overflow-hidden bg-white/[.06] sm:max-w-52"><div className="h-full bg-amber-400 transition-all duration-500" style={{width:`${((current.question_index+1)/interview.turns.length)*100}%`}}/></div></div><h2 className="mt-4 text-lg font-medium leading-7 text-white sm:text-xl sm:leading-8">{current.question}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain your reasoning, reference the implementation, and mention tradeoffs…" className="mt-6 min-h-48 w-full resize-y border border-white/[.1] bg-black/20 p-4 text-sm leading-6 text-slate-200 outline-none placeholder:text-[#55514b] transition focus:border-amber-400/40 sm:min-h-52"/><div className="mt-3 flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between"><span className="font-mono text-[9px] uppercase tracking-wider text-[#55514b]">Use evidence from the repository</span><button disabled={sending||!answer.trim()} className="inline-flex min-h-11 w-full items-center justify-center gap-2 border border-amber-400/40 bg-amber-400 px-5 py-3 text-sm font-semibold text-black transition hover:bg-amber-300 disabled:cursor-not-allowed disabled:opacity-40 sm:w-auto">{sending?<Loader2 size={16} className="animate-spin"/>:<Send size={16}/>} Submit answer</button></div></div></form>}
    {interview?.status==='completed'&&<div className="mt-7 space-y-4"><div className="card p-6 text-center sm:p-8 reveal"><div className="mx-auto grid h-14 w-14 place-items-center border border-emerald-400/20 bg-emerald-400/[.06] text-emerald-300"><Trophy size={24}/></div><div className="mt-5 font-mono text-[9px] uppercase tracking-[.16em] text-[#66625b]">Interview score</div><div className="mt-1 text-5xl font-semibold">{interview.score??0}<span className="text-2xl text-[#55514b]">/100</span></div><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[#77736c]">{interview.feedback?.summary}</p><Link href={`/repositories/${params.id}/report`} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 border border-amber-400/40 bg-amber-400 px-5 py-3 text-sm font-semibold text-black transition hover:bg-amber-300 sm:w-auto">View developer report <ArrowRight size={16}/></Link></div>{interview.turns.map((t,i)=><div key={t.id} className="card p-4 reveal" style={{animationDelay:`${Math.min(i,7)*45}ms`}}><div className="flex gap-3"><span className="font-mono text-[10px] text-[#55514b]">{String(i+1).padStart(2,'0')}</span><div className="min-w-0 flex-1"><div className="text-sm font-medium text-white">{t.question}</div><div className="mt-3 border border-white/[.06] bg-white/[.02] p-3 text-sm leading-6 text-[#77736c]">{t.answer}</div>{t.evaluation&&<div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="border border-emerald-400/10 bg-emerald-400/[.04] p-3 text-xs text-[#77736c]"><span className="block font-mono text-[9px] uppercase text-emerald-300">Score</span><b className="mt-1 block text-lg text-white">{t.evaluation.score}/100</b></div><div className="border border-white/[.06] bg-white/[.02] p-3 text-xs text-[#77736c] sm:col-span-2"><span className="block font-mono text-[9px] uppercase text-amber-300">Verdict</span><span className="mt-1 block">{t.evaluation.verdict}</span></div></div>}</div></div></div>)}</div>}
  </main></div>
}
