services:
  - type: web
    name: repolens-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_BASE_URL
        sync: false
      - key: AI_MODEL
        value: gpt-4o-mini
    healthCheckPath: /health
