'use client'
import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, Github, Loader2, ShieldCheck } from 'lucide-react'
import { Nav } from '@/components/Nav'
import { createAnalysis } from '@/lib/api'

export default function AnalyzePage() {
  const router = useRouter(); const [url,setUrl]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const result=await createAnalysis(url.trim());router.push(`/repositories/${result.id}`)}catch(err:any){setError(err.message||'Unable to start analysis')}finally{setLoading(false)}}
  return <div className="min-h-screen"><Nav/><main className="mx-auto flex min-h-[calc(100vh-56px)] max-w-4xl items-start px-4 py-12 sm:px-6 sm:py-20 lg:px-8 lg:items-center"><div className="w-full reveal"><div className="font-mono text-[10px] uppercase tracking-[.18em] text-amber-400">/ new analysis</div><h1 className="mt-3 text-[2.35rem] font-semibold tracking-[-.04em] sm:text-5xl">Bring a repository.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#77736c] sm:text-base">RepoAutopsy will fetch the public GitHub repository, inspect its structure and prepare a technical review.</p>
    <form onSubmit={submit} className="card relative mt-8 overflow-hidden p-4 sm:mt-10 sm:p-7"><div className="scan-overlay opacity-40"/><label className="relative text-sm font-medium text-[#d7d3cb]">GitHub repository URL</label><div className="relative mt-3 flex min-h-14 items-center gap-2 border border-white/[.1] bg-black/20 px-3 transition focus-within:border-amber-400/40 sm:px-4"><Github size={17} className="shrink-0 text-[#66625b]"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/owner/repository" className="min-w-0 flex-1 bg-transparent py-3 text-sm text-white outline-none placeholder:text-[#4f4c47]" required/></div>{error&&<div className="relative mt-3 border border-rose-400/20 bg-rose-400/[.06] p-3 text-sm leading-5 text-rose-300">{error}</div>}<button disabled={loading} className="relative mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 border border-amber-400/40 bg-amber-400 px-5 py-3 text-sm font-semibold text-black transition hover:bg-amber-300 disabled:cursor-not-allowed disabled:opacity-50">{loading?<Loader2 size={17} className="animate-spin"/>:<ArrowRight size={17}/>} {loading?'Starting analysis…':'Analyze repository'}</button><div className="relative mt-4 flex items-start gap-2 border-t border-white/[.07] pt-4 text-[11px] leading-5 text-[#66625b]"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-emerald-400"/>Only GitHub repository URLs are accepted. File-count, size and path-safety limits are applied before processing.</div></form>
    <div className="mt-5 grid gap-2 text-[10px] font-mono uppercase tracking-wider text-[#55514b] sm:grid-cols-3"><div className="border border-white/[.07] px-3 py-2">01 · Fetch</div><div className="border border-white/[.07] px-3 py-2">02 · Analyze</div><div className="border border-white/[.07] px-3 py-2">03 · Interview</div></div>
  </div></main></div>
}
